name: Aspectlux
favicon: null
layout_spectrum: 0.94956
typography_spectrum: 0.75824
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.35309606115333736
  lightness: 0.19535746378824115
  saturation: 0.6014185701496899
  rhythmicContrast: 0.617786216083914
purpose: []
